const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs=require('fs'),assert=require('assert/strict');
const feed=JSON.parse(fs.readFileSync(process.env.QBANCO_FEED_FILE,'utf8'));
(async()=>{const browser=await chromium.launch({headless:true,channel:"msedge"});let checks=0;const check=(condition)=>{assert.ok(condition);checks++;};
 const context=await browser.newContext({viewport:{width:390,height:844}});const page=await context.newPage();let account=null,mode='ok';let progressRequests=0;
 await context.route('**/api/account/session',r=>r.fulfill({json:{session:account?{user:{id:account}}:null}}));
 await context.route('**/generated-questions.json',r=>mode==='fail'?r.fulfill({status:503,body:'unavailable'}):r.fulfill({json:mode==='empty'?[]:feed}));
 page.on('request',r=>{if(r.method()==='POST')progressRequests++;});
 await page.goto('http://127.0.0.1:8080/qbanco/');await page.getByRole('button',{name:'Start today’s set'}).waitFor();
 check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.screenshot({path:'work/qbanco-mobile.png',fullPage:true});
 await page.getByRole('button',{name:'Start today’s set'}).click();check(await page.locator('.rationale').count()===0);check(await page.getByRole('link',{name:/cdc.gov/}).count()===0);
 await page.getByRole('button',{name:'Submit answer'}).click();check((await page.locator('#notice').innerText()).includes('Choose at least'));
 await page.locator('input[value="B"]').check();await page.getByRole('button',{name:'Submit answer'}).click();check(await page.locator('#feedback').innerText()==='Not quite');check(await page.locator('.explanation').count()===4);check(await page.locator('.source-list a').count()===2);
 await page.getByRole('button',{name:'Bookmark',exact:true}).click();await page.reload();await page.getByRole('button',{name:'Continue today’s set'}).waitFor();check((await page.evaluate(()=>JSON.parse(localStorage.getItem('qbanco:v1:guest')))).seen.length===1);
 await page.getByRole('button',{name:'Missed questions',exact:true}).click();await page.getByRole('button',{name:'Retry',exact:true}).click();check(await page.locator('.rationale').count()===0);check(await page.locator('input:checked').count()===0);await page.locator('input[value="A"]').check();await page.getByRole('button',{name:'Submit answer'}).click();check(await page.locator('#feedback').innerText()==='Correct');await page.getByRole('button',{name:'View session summary'}).click();check((await page.locator('main').innerText()).includes('1 / 1 correct'));
 await page.getByRole('button',{name:'Browse topics',exact:true}).click();await page.getByRole('button',{name:/Pediatrics/}).click();await page.getByRole('button',{name:'Practice',exact:true}).click();await page.locator('input[value="A"]').check();await page.getByRole('button',{name:'Submit answer'}).click();check(await page.locator('#feedback').innerText()==='Not quite');check(await page.locator('.explanation').count()===5);
 await page.screenshot({path:'work/qbanco-rationale-mobile.png',fullPage:true});
 await page.getByRole('button',{name:'View session summary'}).click();await page.getByRole('button',{name:'Retry this set'}).click();for(const a of ['A','B','C'])await page.locator(`input[value="${a}"]`).check();await page.getByRole('button',{name:'Submit answer'}).click();check(await page.locator('#feedback').innerText()==='Correct');
 // Reuse existing account API and verify profile changes do not carry answers across.
 account='test-account';await page.evaluate(()=>window.SiahverseAccount.auth.getSession());await page.waitForFunction(()=>document.querySelector('#identity').textContent.startsWith('Siahverse account'));check(await page.locator('.rationale').count()===0);check(await page.evaluate(()=>JSON.parse(localStorage.getItem('qbanco:v1:test-account')).seen.length)===0);
 account=null;await page.evaluate(()=>window.SiahverseAccount.auth.getSession());await page.waitForFunction(()=>document.querySelector('#identity').textContent.startsWith('Guest practice'));check(await page.evaluate(()=>JSON.parse(localStorage.getItem('qbanco:v1:guest')).seen.length)===2);
 await page.getByRole('button',{name:'Reset progress on this device'}).click();await page.getByRole('button',{name:'Cancel',exact:true}).click();check(await page.evaluate(()=>JSON.parse(localStorage.getItem('qbanco:v1:guest')).seen.length)===2);
 await page.getByRole('button',{name:'Reset progress on this device'}).click();await page.getByRole('button',{name:'Reset progress',exact:true}).click();check(await page.evaluate(()=>JSON.parse(localStorage.getItem('qbanco:v1:guest')).seen.length)===0);
 mode='fail';await page.reload();await page.getByRole('heading',{name:'Question bank unavailable'}).waitFor();check(await page.locator('input[name=answer]').count()===0);mode='empty';await page.getByRole('button',{name:'Try loading again'}).click();await page.getByRole('heading',{name:'No questions available yet'}).waitFor();check(await page.locator('input[name=answer]').count()===0);
 mode='ok';await page.getByRole('button',{name:'Refresh question bank'}).click();await page.getByRole('button',{name:'Start today’s set'}).waitFor();await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'work/qbanco-desktop.png',fullPage:true});check(progressRequests===0);
 // Storage blocked is an explicit temporary session, not a crash.
 const blocked=await browser.newContext();await blocked.route('**/api/account/session',r=>r.fulfill({json:{session:null}}));await blocked.route('**/generated-questions.json',r=>r.fulfill({json:feed}));await blocked.addInitScript(()=>{Storage.prototype.getItem=()=>{throw Error('blocked')};Storage.prototype.setItem=()=>{throw Error('blocked')};});const bp=await blocked.newPage();await bp.goto('http://127.0.0.1:8080/qbanco/');await bp.getByRole('button',{name:'Start today’s set'}).waitFor();check((await bp.locator('#identity').innerText()).includes('Temporary'));
 console.log(`${checks} browser assertions passed; mobile and desktop screenshots saved.`);await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
