import {TOPICS,dayKey,fresh,storageKey,readProgress,dailySet,record,loadFeed} from './core.mjs';
const main=document.querySelector('main'),notice=document.querySelector('#notice');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let bank=[],user=null,p=fresh(),persistent=true,view='home',session=null,feedState='loading',feedErrors=0,identityReady=false,canWrite=true;
function inform(s){notice.textContent=s;}
function save(){if(!canWrite)return;try{localStorage.setItem(storageKey(user),JSON.stringify(p));}catch{persistent=false;inform('Device storage is unavailable or full. Progress is kept only until this page closes.');}identity();}
function identity(){document.querySelector('#identity').textContent=(user?'Siahverse account':'Guest practice')+' · '+(persistent?'Saved on this device only':'Temporary session only');}
function switchIdentity(id){if(identityReady&&id===user)return;user=id;session=null;view="home";try{p=readProgress(localStorage,user);persistent=true;canWrite=true;}catch{p=fresh();persistent=false;canWrite=false;inform('Saved progress could not be read. Practice is temporary; reset this profile to start saving again.');}identityReady=true;identity();render();}
function button(label,action,extra=''){return `<button data-action="${action}" ${extra}>${label}</button>`;}
function availableDaily(){return dailySet(bank,p,dayKey()).filter(id=>bank.some(q=>q.id===id));}
function navigation(){document.querySelectorAll('[data-view]').forEach(b=>{if(b.dataset.view===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});}
function go(v){session=null;view=v;render();main.focus();}
function render(){navigation();if(session)return renderQuestion();if(feedState==='loading'){main.innerHTML='<p class="loading">Loading your question bank…</p>';return;}
 if(feedState==='error'){main.innerHTML=`<section class="card empty"><h1>Question bank unavailable</h1><p>We couldn’t load the original-question feed. Your saved progress is still on this device.</p>${button('Try loading again','reload')}</section>`;return;}
 if(!bank.length){main.innerHTML=`<section class="card empty"><h1>No questions available yet</h1><p>${feedErrors?'The feed has no valid, ready original questions.':'The question bank is empty.'} Check back when new questions are added.</p>${button('Refresh question bank','reload')}</section>`;return;}
 if(view==='home'){
 const ids=availableDaily();save();const completed=ids.filter(id=>p.attempts[id]).length,attempted=bank.filter(q=>p.attempts[q.id]).length,correct=bank.filter(q=>p.attempts[q.id]?.correct).length;
 main.innerHTML=`<section class="hero"><span class="eyebrow">Nursing practice</span><h1>A little practice.<br>A clearer understanding.</h1><p class="lead">Start with today’s questions, explore a topic, or revisit what you missed. Take your time with the reasoning.</p></section><div class="cards"><section class="card daily"><span class="eyebrow">Daily practice · Pacific time</span><h2>Today’s 10 Questions</h2><div class="count">${ids.length}<small> questions in this set</small></div><p>${ids.length<10?`Only ${ids.length} unseen question${ids.length===1?' is':'s are'} available for this daily set. We won’t silently repeat older questions.`:'A balanced mix of available topics, reserved for today.'}</p><p class="muted">${completed} of ${ids.length} submitted · ${esc(dayKey())}</p><div class="actions">${button(completed===ids.length&&ids.length?'Retry today’s set':completed?'Continue today’s set':'Start today’s set','daily',ids.length?'':'disabled')}</div></section><div class="stack"><section class="card"><span class="eyebrow">Practice your way</span><h2>Browse Topics</h2><p class="muted">Eight nursing topics. Choose where to focus.</p>${button('Explore topics →','topics','class="quiet"')}</section><section class="card"><span class="eyebrow">Make it click</span><h2>Review Missed Questions</h2><p class="muted">${bank.filter(q=>p.attempts[q.id]&&!p.attempts[q.id].correct).length} questions to revisit. Retry with answers hidden.</p>${button('Review missed →','missed','class="quiet"')}</section></div></div><div class="stats"><div class="stat"><strong>${attempted}</strong><span>Questions practiced</span></div><div class="stat"><strong>${attempted?Math.round(correct/attempted*100)+'%':'—'}</strong><span>Latest-attempt accuracy</span></div><div class="stat"><strong>${p.bookmarks.filter(id=>bank.some(q=>q.id===id)).length}</strong><span>Bookmarked</span></div></div><h2 class="section-heading">Explore the question bank</h2>${topicsMarkup()}<p class="muted">Discover daily questions in <a href="/nclexapro/">NCLEXapro on Discord</a>; practice and review here. Your practice history is independent of the bot’s posting history.</p>`;
 }else if(view==='topics'){main.innerHTML=`<section class="hero"><span class="eyebrow">The question bank</span><h1>Browse topics</h1><p class="lead">Practice any question again. Previous answers stay hidden until you submit a new attempt.</p></section>${topicsMarkup()}`;}
 else {const filtered=bank.filter(q=>view==='missed'?p.attempts[q.id]&&!p.attempts[q.id].correct:view==='bookmarks'?p.bookmarks.includes(q.id):q.topicGroup===view);main.innerHTML=`<section class="hero"><span class="eyebrow">Focused practice</span><h1>${esc(view==='missed'?'Missed questions':view==='bookmarks'?'Bookmarks':view)}</h1><p class="lead">${filtered.length} question${filtered.length===1?'':'s'} available. Every retry starts with a fresh answer.</p>${filtered.length?button('Practice this list','list'):''}</section><div class="list">${filtered.length?filtered.map(q=>`<article class="card row"><div><span class="eyebrow">${esc(q.topicGroup)}</span><h2>${esc(q.question)}</h2><p>${p.attempts[q.id]?'Previously attempted':'Not yet attempted'} · ${q.answers.length>1?'Select all that apply':'Single answer'}</p></div>${button(p.attempts[q.id]?'Retry':'Practice','question',`data-id="${esc(q.id)}"`)}</article>`).join(''):'<section class="card empty"><h2>Nothing here yet</h2><p>Try another topic or return after more questions are added.</p></section>'}</div>`;}
}
function topicsMarkup(){return `<div class="topics">${TOPICS.map(t=>`<button class="topic" data-topic="${esc(t)}">${esc(t)}<span>${bank.filter(q=>q.topicGroup===t).length} questions →</span></button>`).join('')}</div>`;}
function start(ids,label){const questions=ids.map(id=>bank.find(q=>q.id===id)).filter(Boolean);if(!questions.length)return;session={questions,index:0,results:[],label,submitted:false,selected:[]};renderQuestion();main.focus();}
function renderQuestion(){const s=session,q=s.questions[s.index];main.innerHTML=`<section class="session"><div class="session-top"><span>${esc(s.label)} · ${s.index+1} / ${s.questions.length}</span>${button('Exit session','exit','class="quiet"')}</div><progress value="${s.index}" max="${s.questions.length}" aria-label="Questions completed"></progress><article class="card"><div class="session-top"><span class="eyebrow">${esc(q.topicGroup)}</span>${button(p.bookmarks.includes(q.id)?'Bookmarked ✓':'Bookmark','bookmark',`class="quiet" aria-pressed="${p.bookmarks.includes(q.id)}"`)}</div><h1 class="question">${esc(q.question)}</h1><form id="answer-form"><fieldset class="choices"><legend>${q.answers.length>1?'Select all that apply. All correct options and no incorrect options are required.':'Choose one answer.'}</legend>${q.choices.map(c=>`<label class="option"><input name="answer" type="${q.answers.length>1?'checkbox':'radio'}" value="${c.letter}" ${s.selected.includes(c.letter)?'checked':''} ${s.submitted?'disabled':''}><span><strong>${c.letter}.</strong> ${esc(c.text)}</span></label>`).join('')}</fieldset>${s.submitted?'':'<button type="submit">Submit answer</button>'}</form>${s.submitted?rationaleMarkup(q):''}</article></section>`;if(s.submitted)document.querySelector('#feedback').focus();}
function rationaleMarkup(q){const correct=session.results.at(-1).correct;return `<section class="rationale"><h2 id="feedback" tabindex="-1" class="result ${correct?'':'incorrect'}">${correct?'Correct':'Not quite'}</h2><p>Your answer: ${esc(session.selected.join(', '))}. Correct answer: <strong>${q.answers.join(', ')}</strong>.</p>${q.answers.length>1?'<p>Select-all-that-apply uses exact-match grading. Partial selections receive no credit.</p>':''}${q.choices.map(c=>`<div class="explanation"><strong>${c.letter} · ${q.answers.includes(c.letter)?'Correct option':'Incorrect option'}</strong><p>${esc(q.explanations[c.letter])}</p></div>`).join('')}<h3>Rationale sources</h3><p class="muted">${esc(q.rationale_source)}</p><ul class="source-list">${q.source_urls.map(url=>`<li><a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(url)}</a></li>`).join('')}</ul><div class="actions">${button(session.index+1===session.questions.length?'View session summary':'Next question','next')}</div></section>`;}
function summary(){const s=session,count=s.results.filter(r=>r.correct).length;main.innerHTML=`<section class="session card"><span class="eyebrow">Session complete</span><h1>You’ve reviewed ${s.results.length} questions.</h1><h2>${count} / ${s.results.length} correct · ${Math.round(count/s.results.length*100)}%</h2><p class="muted">This score belongs to this session. Dashboard accuracy uses your latest attempt on each question.</p><div class="list">${s.results.map((r,i)=>`<div class="explanation"><strong>${i+1}. ${r.correct?'Correct':'Missed'} · ${esc(r.q.topicGroup)}</strong><p>${esc(r.q.question)}</p></div>`).join('')}</div><div class="actions">${button('Return to dashboard','home')}${button('Retry this set','retry','class="quiet"')}${button('Review missed','missed','class="quiet"')}</div></section>`;main.focus();}
main.addEventListener('submit',e=>{e.preventDefault();if(!session||session.submitted)return;const selected=[...new FormData(e.target).getAll('answer')];if(!selected.length){inform('Choose at least one answer before submitting.');return;}inform('');const q=session.questions[session.index];session.selected=selected;session.submitted=true;session.results.push({q,correct:record(p,q,selected)});save();renderQuestion();});
main.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.topic)return go(b.dataset.topic);const action=b.dataset.action;if(['home','topics','missed','bookmarks'].includes(action))return go(action);if(action==='reload')return refresh();if(action==='daily'){const ids=availableDaily(),remaining=ids.filter(id=>!p.attempts[id]);return start(remaining.length?remaining:ids,'Today’s set');}if(action==='question')return start([b.dataset.id],'Practice');if(action==='list')return start(bank.filter(q=>view==='missed'?p.attempts[q.id]&&!p.attempts[q.id].correct:view==='bookmarks'?p.bookmarks.includes(q.id):q.topicGroup===view).map(q=>q.id),view);if(action==='exit')return go('home');if(action==='bookmark'){const q=session.questions[session.index];p.bookmarks=p.bookmarks.includes(q.id)?p.bookmarks.filter(id=>id!==q.id):[...p.bookmarks,q.id];save();b.textContent=p.bookmarks.includes(q.id)?'Bookmarked ✓':'Bookmark';b.setAttribute('aria-pressed',String(p.bookmarks.includes(q.id)));}if(action==='next'){if(session.index+1===session.questions.length)return summary();session.index++;session.submitted=false;session.selected=[];renderQuestion();main.focus();}if(action==='retry')return start(session.questions.map(q=>q.id),session.label);});
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.view)));
const dialog=document.querySelector('dialog');document.querySelector('#reset').onclick=()=>dialog.showModal();document.querySelector('#cancel-reset').onclick=()=>dialog.close();document.querySelector('#confirm-reset').onclick=()=>{try{localStorage.removeItem(storageKey(user));persistent=true;}catch{persistent=false;}canWrite=true;p=fresh();session=null;view='home';dialog.close();inform('Progress, bookmarks, and daily assignments for this profile were reset.');render();};
// Refresh in-memory state after another tab changes this profile; never overwrite its newer attempts.
window.addEventListener('storage',e=>{if(e.key===storageKey(user)||e.key===null){try{p=readProgress(localStorage,user);session=null;inform('Progress updated in another tab. Your session has returned to the dashboard.');view='home';render();}catch{inform('Progress changed in another tab but could not be read. Reload before continuing.');}}});
async function refresh(){feedState='loading';session=null;render();try{const result=await loadFeed();bank=result.questions;feedErrors=result.errors.length;feedState='ready';inform(feedErrors?`${feedErrors} invalid or unready feed item(s) were excluded.`:'');}catch{feedState='error';}render();}
switchIdentity(null);
if(window.SiahverseAccount){window.SiahverseAccount.auth.onAuthStateChange((event,s)=>switchIdentity(s?.user.id||null));}
await refresh();
